### PR TITLE
Fixed message.reCAPTCHA.settings Placement

### PR DESCRIPTION
**Pull request by fcpwiz**
Moved message.reCAPTCHA.settings below both keys.

### CODE REVIEW

**Comment by fcpwiz** [comment]
BOOM... again

**Comment by tvb** [comment]
Merged!

**Comment by fcpwiz** [comment]
Awesome! And that was my first merged pull request! :)

**Comment by tvb** [comment]
Good job and thanks!

**Comment by fcpwiz** [comment]
Will this get bumped to 1.2.5?

**Comment by tvb** [comment]
When I have made new screenshots, yes.

**Comment by fcpwiz** [comment]
Ok cool

**Pull request merged**
