### PR TITLE
Updated to screenshots to fit for the new reCAPTCHA

### PR DESCRIPTION
**Pull request by fcpwiz**

### CODE REVIEW

**Comment by fcpwiz** [comment]
Ok @tvb

**Comment by tvb** [comment]
Almost done :smile:

**Comment by fcpwiz** [comment]
Ok! Also, on the settings page- instead of saying "Got no Keys yet?" I would suggest it saying "Don't have any Keys?"

**Comment by fcpwiz** [comment]
I'll make a pull.

**Comment by tvb** [comment]
Cool. I'll change it right now

**Comment by fcpwiz** [comment]
Here: https://github.com/tvb/reCAPTCHA/pull/7

**Pull request closed without merging**
